Repository silent-readers/joogobooks_front, pull requests merged in 2023-09, with the labels that each got.

#8 ♻️ Refactor : 백엔드 서버와 연동을 위한 경로 수정
  assets/js/bookdetail.js
  assets/js/changepassword.js
  assets/js/chat.js
  assets/js/chatapi.js
  assets/js/comment.js
  assets/js/createpost.js
  assets/js/login.js
  assets/js/mypage.js
  assets/js/mypage_main.js
  assets/js/search.js
  assets/js/shop.js
  assets/js/signup.js
  assets/js/updatePost.js
Labels: enhancement

#9 ♻️ Refactor : 경로 오탈자 수정
  assets/js/authorized.js
Labels: enhancement

#10 🐛 Search 링크 수정
  assets/js/search.js
Labels: 버그 수정

#13 ✨ Feat : 비밀번호 찾기 기능 추가
  assets/html/login.html
  assets/html/passwordSearch.html
  assets/js/passwordSearch.js
Labels: 코드 생성, 코드 수정, 고도화작업

#14 🐛 Fix : 판매자 닉네임 표시 오류 수정
  assets/js/shop.js
Labels: 버그 수정, 코드 수정, 고도화작업

#15 🐛 Fix : 카테고리 검색, 글 번호 오류 수정
  assets/css/search.css
  assets/js/search.js
Labels: 코드 수정, 고도화작업, 코드리팩토링

#16 ✨ Feat : FAQ 관련 UI 생성
  assets/css/fna.css
  assets/html/aboutUs.html
  assets/html/fna.html
  assets/html/joongoReaders.html
  assets/img/card.png
  assets/img/delivery.png
  assets/img/user-img.png
  assets/js/fna.js
Labels: 코드 생성, 코드 수정, 고도화작업
